# Generated by Django 5.1.7 on 2025-04-01 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=12),
            preserve_default=False,
        ),
    ]
