# Generated by Django 5.1.7 on 2025-04-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_investment_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
