# Generated by Django 5.1.7 on 2025-04-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_alter_investment_funds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='funds',
        ),
    ]
